apiVersion: v1
kind: Service
metadata:
  name: anvil-service
spec:
  selector:
    name: anvil-1
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30000
  type: NodePort
