apiVersion: v1
kind: Pod
metadata:
  name: anvil
  labels:
    app.kubernetes.io/name: anvil
spec:
  containers:
    - name: anvil
      image: ghcr.io/foundry-rs/foundry:master
      securityContext:
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 8545
      command: ["anvil"]
      args: ["--port", "$(ANVIL_PORT)", "--fork-url", "$(FORK_URL)"]
      envFrom:
        - secretRef:
            name: secret
        - configMapRef:
            name: anvil-config
---
apiVersion: v1
kind: Service
metadata:
  name: anvil-service
spec:
  selector:
    app.kubernetes.io/name: anvil
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
