---
apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    name: proxy
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
  containers:
    - name: proxy
      image: docker.io/piotr439/proxy:add_transaction
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: ClusterIP
  selector:
    name: proxy
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
