apiVersion: batch/v1
kind: Job
metadata:
  name: juno-setup
spec:
  template:
    spec:
      containers:
        - name: juno-setup
          image: docker.io/piotr439/juno-dbs:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying data for juno instances..." && \
              cp -r /snapshots/juno-sepolia /mnt/data/juno && \
              touch /mnt/data/juno/ready
          volumeMounts:
            - name: juno-setup
              mountPath: /mnt/data/juno
      volumes:
        - name: juno-setup
          persistentVolumeClaim:
            claimName: juno-setup
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juno-setup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
