apiVersion: v1
kind: PersistentVolume
metadata:
  name: juno-pv
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/var/lib/juno"
