apiVersion: v1
kind: Pod
metadata:
  name: juno-db-snapshot
spec:
  initContainers:
    - name: init-copy
      image: docker.io/piotr439/juno-dbs:latest
      command: ["sh", "-c", "cp -r /snapshots/juno-sepolia /var/lib/juno"]
      volumeMounts:
        - name: juno-data-1
          mountPath: /var/lib/juno
  containers:
    - name: juno-placeholder
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: juno-data-1
          mountPath: /var/lib/juno
  volumes:
    - name: juno-data-1
      persistentVolumeClaim:
        claimName: juno-pvc
