apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: juno
spec:
  serviceName: juno
  replicas: 1
  selector:
    matchLabels:
      app: juno
  template:
    metadata:
      labels:
        app: juno
    spec:
      initContainers:
        - name: init-juno
          image: docker.io/busybox:1.37.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for data to be copied by juno-setup job..." && \
              while [ ! -f /mnt/data/juno/ready ]; do \
                echo "Waiting for /mnt/data/juno/ready to be available..."; \
                sleep 5; \
              done; \
              echo "Data is available, starting copying..." && \
              cp -r /mnt/data/juno/juno-sepolia /var/lib/juno
          volumeMounts:
            - name: juno-setup
              mountPath: /mnt/data/juno
            - name: juno
              mountPath: /var/lib/juno
      containers:
        - name: juno
          image: docker.io/nethermind/juno:v0.12.5
          ports:
            - containerPort: 6060
          args:
            - "--http"
            - "--http-port"
            - "$(PORT)"
            - "--http-host"
            - "$(HOST)"
            - "--db-path"
            - "$(DB_PATH)"
            - "--eth-node"
            - "$(ETH_NODE)"
            - "--network"
            - "$(NETWORK)"
          envFrom:
            - configMapRef:
                name: juno-config
          volumeMounts:
            - name: juno
              mountPath: /var/lib/juno
      volumes:
        - name: juno-setup
          persistentVolumeClaim:
            claimName: juno-setup
        - name: juno
          persistentVolumeClaim:
            claimName: juno
  volumeClaimTemplates:
    - metadata:
        name: juno
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 64Gi

---
apiVersion: v1
kind: Service
metadata:
  name: juno
spec:
  clusterIP: None
  selector:
    app: juno
  ports:
    - name: rpc
      protocol: TCP
      port: 6060
      targetPort: 6060
