apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: papyrus
spec:
  serviceName: papyrus
  replicas: 1
  selector:
    matchLabels:
      app: papyrus
  template:
    metadata:
      labels:
        app: papyrus
    spec:
      containers:
        - name: papyrus
          image: ghcr.io/starkware-libs/papyrus:dvir-write_info_13_1-ec0ec35
          args:
            - "--base_layer.node_url"
            - "$(BASE_LAYER_NODE_URL)"
          envFrom:
            - configMapRef:
                name: papyrus-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: papyrus
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: papyrus
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 24Gi
---
apiVersion: v1
kind: Service
metadata:
  name: papyrus
spec:
  clusterIP: None
  selector:
    app: papyrus
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
