apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-1
  labels:
    name: pathfinder-1
spec:
  containers:
    - name: pathfinder-1
      image: uacias/pathfinder:latest
      args:
        [
          "--ethereum.url",
          "https://eth-mainnet.g.alchemy.com/v2/bkM2DYyg8UBW7zANvO_F9NcagmiqAHRG",
        ]
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-2
  labels:
    name: pathfinder-2
spec:
  containers:
    - name: pathfinder-2
      image: uacias/pathfinder:latest
      args:
        [
          "--ethereum.url",
          "https://eth-mainnet.g.alchemy.com/v2/bkM2DYyg8UBW7zANvO_F9NcagmiqAHRG",
        ]
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-3
  labels:
    name: pathfinder-3
spec:
  containers:
    - name: pathfinder-3
      image: uacias/pathfinder:latest
      args:
        [
          "--ethereum.url",
          "https://eth-mainnet.g.alchemy.com/v2/bkM2DYyg8UBW7zANvO_F9NcagmiqAHRG",
        ]
      ports:
        - containerPort: 80
