apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml

configMapGenerator:
  - name: madara-config
    env: .env.local

secretGenerator:
  - name: madara-secret
    env: .env
