apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - pathfinder-pv.yaml
  # - pathfinder-pvc.yaml
  # - pathfinder-db-snapshot.yaml
  - pathfinder-stateful-set.yaml
  - pathfinder.yaml
