apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-db-snapshot
spec:
  containers:
    - name: pathfinder-fetcher
      image: uacias/pathfinder-db-snap2:latest
      volumeMounts:
        - mountPath: /mnt/data/pathfinder
          name: pathfinder-volume
        - mountPath: /mnt/data/pathfinder-2
          name: pathfinder-volume-2
  volumes:
    - name: pathfinder-volume
      persistentVolumeClaim:
        claimName: pathfinder-pvc
    - name: pathfinder-volume-2
      persistentVolumeClaim:
        claimName: pathfinder-pvc-2
