apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-1
  labels:
    name: pathfinder-1
spec:
  initContainers:
    - name: wait-for-db-snapshot
      image: docker.io/busybox
      command:
        [
          "sh",
          "-c",
          'while [ ! -f /usr/share/pathfinder/data/testnet-sepolia.sqlite ]; do echo "Waiting for snapshot"; sleep 10; done; echo "Snapshot found, starting pathfinder..."',
        ]
      volumeMounts:
        - name: pathfinder-data-1
          mountPath: /usr/share/pathfinder/data
  containers:
    - name: pathfinder-1
      image: eqlabs/pathfinder:v0.14.1
      ports:
        - containerPort: 80
        - containerPort: 9090
        - containerPort: 9545
      env:
        - name: PATHFINDER_MONITOR_ADDRESS
          value: "0.0.0.0:9090"
        - name: PATHFINDER_HTTP_RPC_ADDRESS
          value: "0.0.0.0:9545"
        - name: PATHFINDER_ETHEREUM_API_URL
          value: "http://anvil-service:8545"
        - name: PATHFINDER_NETWORK
          value: "sepolia-testnet"
      volumeMounts:
        - name: pathfinder-data-1
          mountPath: /usr/share/pathfinder/data
  volumes:
    - name: pathfinder-data-1
      persistentVolumeClaim:
        claimName: pathfinder-pvc
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-2
  labels:
    name: pathfinder-2
spec:
  initContainers:
    - name: wait-for-db-snapshot
      image: docker.io/busybox
      command:
        [
          "sh",
          "-c",
          'while [ ! -f /usr/share/pathfinder/data/testnet-sepolia.sqlite ]; do echo "Waiting for snapshot"; sleep 10; done; echo "Snapshot found, starting pathfinder..."',
        ]
      volumeMounts:
        - name: pathfinder-data-2
          mountPath: /usr/share/pathfinder/data
  containers:
    - name: pathfinder-2
      image: docker.io/eqlabs/pathfinder:v0.14.1
      ports:
        - containerPort: 80
        - containerPort: 9090
        - containerPort: 9545
      env:
        - name: PATHFINDER_MONITOR_ADDRESS
          value: "0.0.0.0:9090"
        - name: PATHFINDER_HTTP_RPC_ADDRESS
          value: "0.0.0.0:9545"
        - name: PATHFINDER_ETHEREUM_API_URL
          value: "http://anvil-service:8545"
        - name: PATHFINDER_NETWORK
          value: "sepolia-testnet"
      volumeMounts:
        - name: pathfinder-data-2
          mountPath: /usr/share/pathfinder/data
  volumes:
    - name: pathfinder-data-2
      persistentVolumeClaim:
        claimName: pathfinder-pvc-2
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
---
apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service-1
spec:
  type: NodePort
  selector:
    name: pathfinder-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: monitor
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30011
    - name: rpc
      protocol: TCP
      port: 9545
      targetPort: 9545
      nodePort: 30021
---
apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service-2
spec:
  type: NodePort
  selector:
    name: pathfinder-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
    - name: monitor
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30012
    - name: rpc
      protocol: TCP
      port: 9545
      targetPort: 9545
      nodePort: 30022
