apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-1
  labels:
    name: pathfinder-1
spec:
  containers:
    - name: pathfinder-1
      image: uacias/pathfinder:latest
      ports:
        - containerPort: 80
        - containerPort: 9090
        - containerPort: 9545
      env:
        - name: PATHFINDER_MONITOR_ADDRESS
          value: "0.0.0.0:9090"
        - name: PATHFINDER_HTTP_RPC_ADDRESS
          value: "0.0.0.0:9545"
        - name: PATHFINDER_ETHEREUM_API_URL
          value: "http://anvil-service:8545"
        - name: PATHFINDER_NETWORK
          value: "sepolia-testnet"
---
apiVersion: v1
kind: Pod
metadata:
  name: pathfinder-2
  labels:
    name: pathfinder-2
spec:
  containers:
    - name: pathfinder-2
      image: uacias/pathfinder:latest
      ports:
        - containerPort: 80
        - containerPort: 9090
        - containerPort: 9545
      env:
        - name: PATHFINDER_MONITOR_ADDRESS
          value: "0.0.0.0:9090"
        - name: PATHFINDER_HTTP_RPC_ADDRESS
          value: "0.0.0.0:9545"
        - name: PATHFINDER_ETHEREUM_API_URL
          value: "http://anvil-service:8545"
        - name: PATHFINDER_NETWORK
          value: "sepolia-testnet"
---
apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service-1
spec:
  type: NodePort
  selector:
    name: pathfinder-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: monitor
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30011
    - name: rpc
      protocol: TCP
      port: 9545
      targetPort: 9545
      nodePort: 30021
---
apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service-2
spec:
  type: NodePort
  selector:
    name: pathfinder-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
    - name: monitor
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30012
    - name: rpc
      protocol: TCP
      port: 9545
      targetPort: 9545
      nodePort: 30022
