apiVersion: batch/v1
kind: Job
metadata:
  name: pathfinder-db-snapshot-job
spec:
  template:
    metadata:
      name: pathfinder-db-snapshot
    spec:
      containers:
        - name: init-copy
          image: docker.io/uacias/patfinder-dbs:latest
          command:
            [
              "sh",
              "-c",
              "cp /mnt/data/original/testnet-sepolia.sqlite /mnt/data/pathfinder/testnet-sepolia.sqlite && cp /mnt/data/original/testnet-sepolia.sqlite /mnt/data/pathfinder-2/testnet-sepolia.sqlite",
            ]
          volumeMounts:
            - mountPath: /mnt/data/pathfinder
              name: pathfinder-volume
            - mountPath: /mnt/data/pathfinder-2
              name: pathfinder-volume-2
      restartPolicy: OnFailure
      volumes:
        - name: pathfinder-volume
          persistentVolumeClaim:
            claimName: pathfinder-pvc
        - name: pathfinder-volume-2
          persistentVolumeClaim:
            claimName: pathfinder-pvc-2
