name: Build Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    name: Build project - rust ${{ matrix.toolchain }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build project
        run: cargo build --all --all-features
