name: Code Quality Checks

on:
  push:
    branches: [201-workflows-enhancement]
  pull_request:
    branches: [main]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    name: Code Quality Checks - rust ${{ matrix.toolchain }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      
      - name: Check Rust version
        run: rustc --version && cargo clippy --version


      - name: Check code formatting with cargo fmt
        run: cargo fmt -- --check

      - name: Lint code with cargo clippy
        run: cargo clippy -- -D warnings
